### ISSUE TITLE
"must be a relative utf-8 path" when giving a relative path for the directory (with a downloaded binary of arx)

### ISSUE THREAD

**Issue by mgautierfr** [jubako/arx#32]
Same issue but with a local path for the directory (with a downloaded binary of arx):

> arx create -o irstea_documents.arx -r Documents
> 
> Compressed Cluster   : ############################################+ 515  / 516 
> Uncompressed Cluster : --------------------------------------------- 0    / 1   Well, this is embarrassing.
> 
> arx had a problem and crashed. To help us diagnose the problem you can send us a crash report.
> 
> We have generated a report file at "/tmp/report-ddf531c4-69ad-476d-9f5b-c602edea3b20.toml". Submit an issue or email with the subject of "arx Crash Report" and include the report as an attachment.
> 
> - Homepage: https://github.com/jubako/arx
> - Authors: Matthieu Gautier <mgautier@kymeria.fr>
> 
> We take privacy seriously, and do not perform any automated error collection. In order to improve the software, we rely on people to submit reports.
> 
> Thank you kindly!

then:

> christo:~$ cat /tmp/report-ddf531c4-69ad-476d-9f5b-c602edea3b20.toml
> "name" = "arx"
> "operating_system" = "Ubuntu 22.04 (jammy) [64-bit]"
> "crate_version" = "0.2.1"
> "explanation" = """
> Panic occurred in file 'libarx/src/create/fs_adder.rs' at line 88
> """
> "cause" = "\"/home/christo/Documents/Pôle\" must be a relative utf-8 path"
> "method" = "Panic"
> "backtrace" = """
> 
>    0: 0x651652a4739c - libarx::create::entry_store_creator::DirEntry::add_entry::hfac430b68bc9369a
>    1: 0x651652a479d8 - libarx::create::entry_store_creator::DirEntry::add::h6a26588866a85f93
>    2: 0x651652a47c2d - libarx::create::entry_store_creator::DirEntry::add::h6a26588866a85f93
>    3: 0x651652a5eee1 - arx::create::create::h0d31a0a1c81133f8
>    4: 0x651652a036c0 - arx::main::h8e785563c91bb87e
>    5: 0x651652a74d63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h512139b71798be16
>    6: 0x651652a0e9d2 - main
>    7: 0x7345bdc29d90 - __libc_start_call_main
>                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
>    8: 0x7345bdc29e40 - __libc_start_main_impl
>                 at ./csu/../csu/libc-start.c:392
>    9: 0x6516529f7255 - _start
>   10:        0x0 - <unresolved>"""
> christo:~$

_Originally posted by @cchristofr in https://github.com/jubako/arx/issues/31#issuecomment-2238996999_

**Comment by mgautierfr** [comment]
@cchristofr I cannot reproduce the bug on my side.

Have you some specific setup as symlink/hardlink or mouted directory in `/home/chisto/Documents` ? Especially about the `Pôle` subdirectory ?

**Comment by mgautierfr** [comment]
Does `Pôle` is the full name of the directory or it is only the beginning as in `Pôle commercial` ?

**Comment by cchristofr** [comment]
It's the full name.

Le lun. 22 juil. 2024, 11:45, Matthieu Gautier ***@***.***> a
écrit :

**Comment by mgautierfr** [comment]
What is your distribution ?
Can you give me the output of `env | grep LANG` please ?

**Comment by cchristofr** [comment]
"operating_system" = "Ubuntu 22.04 (jammy) [64-bit]"
LANG : .FR.UTF-8

**Comment by mgautierfr** [comment]
Can you test with this binary : https://github.com/jubako/arx/actions/runs/10096607935/artifacts/1740063007 from the PR #36 ?

On top of the change of the PR, it is based on the main branch which change a lot of things since release 0.2.1

**Comment by cchristofr** [comment]
Bonjour Matthieu

Many thanks for this PR.
It seems OK to me.
I've created an archive of the directory for which I previously had a
problem.
No errors.
The archive's size is 34 Go. I'm impressed by ARX when I mount this archive
: I can access all documents as quick as in the original directory !

Very good work !
Christophe

**Comment by mgautierfr** [comment]
Bonjour Christophe,

Thanks to you for testing arx. I'm glade you like the result.

For my information, what is the size (in bytes and number of files, roughly) of your `Documents` directory ? Do you have good compression ratio ?

**Comment by cchristofr** [comment]
Hi Matthieu

here are 2 examples:

   - a directory with mainly PDF files :
   - original size: 240 Mo, ~400 files
      - arx : 220 Mo
      - zip : 195 Mo
      - 7z : 180 Mo
   - My "Documents" folder on my notebook :
   - 42.7 Go, 56 000 files
      - zip : 37.9 Go
      - arx : 34.2 Go
      - 7z : it takes too much time (~ 4h)


So, 7z has a better compression ratio, but it takes much longer.
ARX is fast if you have enough memory but it seems it doesn't have the best
compression ratio.
ARX seems more suitable for big archives.

regards
Christophe

**Comment by mgautierfr** [comment]
Thanks for the input.
Arx by default use zstd compresssion level 5. 7z is using lzma which has a bit better compression ratio but is slower.

You can give the option `-c lzma=9` or `-c zstd=19` to use a better compression algorithm/level.
Archive creation should take more time. Decompression with lzma should bit slower with lzma (if perceptible) and identical with zstd.
