### ISSUE TITLE
[Documentation] How compression level is choice in arx

### ISSUE THREAD

**Issue by father-mande** [jubako/arx#60]
Hi,

Using last Github (adding feature lzma) : 
.....
arx create --list-compressions
Available compressions :
 - None
 - lzma (level 0->9)
 - zstd (level -22->22)
.....

How arx select level (compression algorithm have an argument in create action) to use ... based on file type or is it dynamic per file or ...
semes user don't have the hand on this value ?
Just For Information ... because at this time (after multiple tests) result seems adapted et don't need any control.

Philippe.

**Comment by mgautierfr** [comment]
Jubako is automatically selecting if content must be compressed or not based on Shannon entropy of the beginning of the content. The idea is to not compress content already compressed (video, images).
It is possible to force compression or not at API level but arx don't use it.

There is currently only one compression algorithm used at the same time in an archive but it is mainly a library limitation than a file format one.

You can select the compression algorithm to use by using the option `--compression <algorithm>` or `--compression <algorithm>=<level>`. `None` compression means that content is never compressed.
