### ISSUE TITLE
[INFO] new prerequisite for compiling arx on arm64

### ISSUE THREAD

**Issue by father-mande** [jubako/arx#64]
Hi,

After some fail ... just to remember (because I don'tread it before)

**arx 0.3.1 require :** 
... python 3.8 or +
... libpython3.8-dev or + (generate a fail at end of arx binary (libarx) generation 
error: linking with `cc` failed: exit status: 1
...
  = note: /bin/ld: cannot find -lpython3.10: No such file or directory
          collect2: error: ld returned 1 exit status
error: could not compile `python-libarx` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

Is it possible to have a list of Linux dependencies, updated at each new version (if changed ) ?

NB rustsh is updated : 
root@AS3302Tv2aphil:/opt/from_git/arx# cargo -V
cargo 1.81.0 (2dbb1af80 2024-08-20)
root@AS3302Tv2aphil:/opt/from_git/arx# rustc -V
rustc 1.81.0 (eeb90cda1 2024-09-04)

Philippe.

**Comment by mgautierfr** [comment]
This is because of the new (indeed) python wrapping around libarx.

By default `cargo build` build all packages in the workspace. You can only build `arx` package (and so only arx binary) using `cargo build -p arx`
