### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by mbridon** [jubako/arx#90]
I just tried `rust2rpm` to package `arx` for Fedora, and it complained about there not being a license file:

```
$ rust2rpm arx
Downloading arx-0.3.2.crate: 100%|███████████████████████████████████████████████████████████████████████████████████| 26.5k/26.5k [00:00<00:00, 223kB/s]
ERROR: No license files were detected. In almost all cases, this is an issue
       with the upstream project that should be reported.
• To temporarily ignore this issue, use the '--ignore-missing-license-files' /
  '-I' flag - for example, when manually including license files from the
  upstream project, or for test builds.
```

I think you need to declare the crate as having a license **and** a license file? :thinking:

**Comment by mbridon** [comment]
Right: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

**Comment by mgautierfr** [comment]
There is already https://github.com/jubako/arx/blob/main/LICENSE-MIT

**Comment by mbridon** [comment]
Yes, but it is not declared in Cargo.toml as an actual license file, hence #91  :wink:
